export const FETCH_STORIES_REQUEST = 'FETCH_STORIES_REQUEST';
export const FETCH_STORIES_SUCCESS = 'FETCH_STORIES_SUCCESS';
export const FETCH_STORIES_FAILURE = 'FETCH_STORIES_FAILURE';

export const UPVOTE_CLICK = 'UPVOTE_CLICK';
export const UPVOTE_UPDATE = 'UPVOTE_UPDATE';
export const UPVOTE_UPDATE_SUCCESS = 'UPVOTE_UPDATE_SUCCESS';
export const NOMINATION_CLICK = 'NOMINATION_CLICK';

